//////////////////////////////////////////////////
const planetsInformation = [
  {
    radius: 10,
    segments: [40, 20],
    distance: 0,
    revolutionSpeed: 0,
    rotationSpeed: 0.4,
    texture: "textures/sun.jpg",
    light: { color: 0xffffff, intensity: 15000 },
    name: "sun",
    base: "scene",
  },
  {
    radius: 1,
    distance: 36,
    revolutionSpeed: 1.4,
    rotationSpeed: 1,
    texture: "textures/earth.jpg",
    name: "earth",
    base: "sun",
  },
  {
    radius: 0.15,
    segments: [20, 10],
    distance: 2.25,
    revolutionSpeed: 7,
    rotationSpeed: 1.5,
    color: 0xb38769,
    name: "satellite-1",
    base: "earth",
  },
  {
    radius: 0.2,
    segments: [20, 10],
    distance: 3.25,
    revolutionSpeed: 8,
    rotationSpeed: 2,
    color: "gray",
    name: "satellite-2",
    base: "earth",
  },
  {
    radius: 0.5,
    segments: [24, 12],
    distance: 20,
    revolutionSpeed: 3,
    rotationSpeed: 1.2,
    texture: "textures/mercury.jpg",
    name: "mercury",
    base: "sun",
  },
  {
    radius: 0.85,
    distance: 30,
    revolutionSpeed: 2.2,
    rotationSpeed: 1,
    texture: "textures/venus.jpg",
    name: "venus",
    base: "sun",
  },
  {
    radius: 0.72,
    distance: 42,
    revolutionSpeed: 1,
    rotationSpeed: 1,
    texture: "textures/mars.jpg",
    name: "mars",
    base: "sun",
  },
  {
    radius: 1.6,
    distance: 58,
    revolutionSpeed: 0.8,
    rotationSpeed: 1,
    texture: "textures/jupiter.jpg",
    name: "jupiter",
    base: "sun",
  },
  {
    radius: 1.48,
    distance: 70,
    revolutionSpeed: 0.7,
    rotationSpeed: 0.8,
    texture: "textures/saturn.jpg",
    ring: { texture: "textures/saturn ring.png", innerRadius: 2, outerRadius: 5 },
    name: "saturn",
    base: "sun",
  },
  {
    radius: 1.2,
    distance: 82,
    revolutionSpeed: 0.56,
    rotationSpeed: 0.5,
    texture: "textures/uranus.jpg",
    ring: { texture: "textures/uranus ring.png", innerRadius: 2, outerRadius: 4 },
    name: "uranus",
    base: "sun",
  },
  {
    radius: 0.95,
    distance: 90,
    revolutionSpeed: 0.5,
    rotationSpeed: 0.5,
    texture: "textures/neptune.jpg",
    name: "neptune",
    base: "sun",
  },
  {
    radius: 0.48,
    segments: [24, 12],
    distance: 100,
    revolutionSpeed: 0.6,
    rotationSpeed: 0.5,
    texture: "textures/pluto.jpg",
    name: "pluto",
    base: "sun",
  },
];

//////////////////////////////////////////////////

export default planetsInformation;
